<?php
/**
 * Register the Twig engine in Drupal.
 *
 * @implements hook_system_theme_engine_info()
 */

/**
 * Implements hook_boot().
 *
 * Check if the needed classes can be autoloaded or not.
 * If they can not be autoloaded try some last resorts and
 * else fail with an exception.
 */
function tfd7_boot()
{
  if (!class_exists('TFD_Cache_Filesystem')) {
    if (file_exists(__DIR__ . '/vendor/autoload.php')) {
      require_once __DIR__ . '/vendor/autoload.php';
    } elseif (file_exists(DRUPAL_ROOT . '/../vendor/autoload.php')) {
      require_once DRUPAL_ROOT . '/../vendor/autoload.php';
    } elseif (file_exists(DRUPAL_ROOT . '/vendor/autoload.php')) {
      require_once DRUPAL_ROOT . '/vendor/autoload.php';
    } else {
      throw new Exception('You need to have some form of autoloading before using TFD7');
    }
  }
}

function tfd7_system_theme_engine_info()
{
  $theme_engines['twig'] = drupal_get_path('module', 'tfd7') . '/twig.engine';
  return $theme_engines;
}

/**
 * Implements hook_stream_wrappers().
 */
function tfd7_stream_wrappers()
{
  $wrappers['twigcache'] = array(
    'name' => t('Twig cache files'),
    'class' => 'TFD7CacheStreamWrapper',
    'description' => t('Twig cache files, prefered outside of webroot'),
    'type' => STREAM_WRAPPERS_LOCAL_HIDDEN,
  );
  return $wrappers;
}

function tfd7_form_system_file_system_settings_alter(&$form, &$form_state, $form_id)
{

  $weight = 10;
  $form['file_public_path']['#weight'] = $weight;
  $weight++;
  if (array_key_exists('file_private_path',$form)){
    $form['file_private_path']['#weight'] = $weight;
    $weight++;
  }


  $form['file_twigcache_path'] = array(
    '#type' => 'textfield',
    '#weight' => $weight,
    '#title' => t('Twigcache file system path'),
    '#default_value' => variable_get('file_twigcache_path', conf_path() . '/files'),
    '#maxlength' => 255,
    '#description' => t('A local file system path where twig cache files will be stored. This directory preferably is located outside the public webroot. The directory must be writable by Drupal'),
    '#after_build' => array('system_check_directory'),
  );
  $weight++;
  if (array_key_exists('file_temporary_path',$form)){
    $form['file_temporary_path']['#weight'] = $weight;
  }
  $form['#submit'][] = 'tfd7_form_system_file_system_settings_submit';
}

function tfd7_form_system_file_system_settings_submit(&$form, &$form_state)
{
  if ($form_state['values']['file_twigcache_path'] !== '') {
    variable_set('file_twigcache_path', $form_state['values']['file_twigcache_path']);
  }
}



/**
 * Implements hook_flush_cashes()
 */
function tfd7_flush_caches()
{
  if (function_exists('twig_clear_cache')) {
    twig_clear_cache();
  }

}

/**
 * The streamwrapper to rule them all ;-)
 *
 * Class TFD7CacheStreamWrapper
 */
class TFD7CacheStreamWrapper extends DrupalPrivateStreamWrapper
{
  /**
   * Returns the directory path where the Twig Cache Files will be stored.
   * @return null|string
   */
  public function getDirectoryPath()
  {
    if (FALSE !== $cache_path = variable_get('file_twigcache_path', FALSE)) {
      return $cache_path;
    } elseif
    (true === variable_get('file_private_path', FALSE)) {
      return 'private://twig_cache';
    } else {
      // Fallback and use the twig_cache folder in public://.
      return 'public://twig_cache';
    }
  }

  /**
   * Twig cache files are not meant to be loaded through a browser!
   * @return bool|string
   */
  public function getExternalUrl()
  {
    return false;
  }
}

