<?php

/**
 * Implements hook_menu().
 */
function palom_content_menu_menu() {
  $items = [];

  $items['node/%node/view/descr'] = [
    'title' => 'Description',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  ];

  return $items;
}

/**
 * Implements hook_url_inbound_alter().
 */
function palom_content_menu_url_inbound_alter(&$path, $original_path, $path_language) {

  $routes = [

    // by city
    '|^city/([0-9]*)/places?|' => 'node/{{m1}}/view/placesbycity',
    '|^city/([0-9]*)/services?|' => 'node/{{m1}}/view/servicesbycity',
    '|^city/([0-9]*)/accommodation?|' => 'node/{{m1}}/view/accommodationbycity',
    '|^city/([0-9]*)/feeding?|' => 'node/{{m1}}/view/feedingbycity',
    '|^city/([0-9]*)/transport?|' => 'node/{{m1}}/view/transportbycity',

    // by place
    '|^place/([0-9]*)/reviews?|' => 'node/{{m1}}/view/reviewsbyplace',
    '|^place/([0-9]*)/accommodation?|' => 'node/{{m1}}/view/accommodationbyplace',
    '|^place/([0-9]*)/feeding?|' => 'node/{{m1}}/view/feedingbyplace',
    '|^place/([0-9]*)/transport?|' => 'node/{{m1}}/view/transportbyplace',

    // by service
    '|^service/([0-9]*)/tours?|' => 'node/{{m1}}/view/toursbyservice',
    '|^service/([0-9]*)/reviews?|' => 'node/{{m1}}/view/reviewsbyservice',

    // geo
    '|^cities?|' => 'geo/cities',
    '|^places?|' => 'geo/places',
    '|^services?|' => 'geo/companies/services',
    '|^accommodation?|' => 'geo/companies/accommodation',
    '|^feeding?|' => 'geo/companies/feeding',
    '|^transport?|' => 'geo/companies/transport',

  ];

  foreach ($routes as $src => $dst){
    if (preg_match($src, $path, $matches)){
      $src_array = [];
      foreach ($matches as $key => $match){
        $src_array[] = "{{m$key}}";
      }
      $path = str_replace($src_array, $matches, $dst);
      break;
    }
  }
}

/**
 * Implements hook_url_outbound_alter().
 */
function palom_content_menu_url_outbound_alter(&$path, &$options, $original_path) {

  $routes = [

    // by city
    '|^node/([0-9]*)/view/placesbycity?|' => 'city/{{m1}}/places',
    '|^node/([0-9]*)/view/servicesbycity?|' => 'city/{{m1}}/services',
    '|^node/([0-9]*)/view/accommodationbycity?|' => 'city/{{m1}}/accommodation',
    '|^node/([0-9]*)/view/feedingbycity?|' => 'city/{{m1}}/feeding',
    '|^node/([0-9]*)/view/transportbycity?|' => 'city/{{m1}}/transport',


    // by place
    '|^node/([0-9]*)/view/reviewsbyplace?|' => 'place/{{m1}}/reviews',
    '|^node/([0-9]*)/view/accommodationbyplace?|' => 'place/{{m1}}/accommodation',
    '|^node/([0-9]*)/view/feedingbyplace?|' => 'place/{{m1}}/feeding',
    '|^node/([0-9]*)/view/transportbyplace?|' => 'place/{{m1}}/transport',


    // by service
    '|^node/([0-9]*)/view/toursbyservice?|' => 'service/{{m1}}/tours',
    '|^node/([0-9]*)/view/reviewsbyservice?|' => 'service/{{m1}}/reviews',

    // geo
    '|^geo/cities?|' => 'cities',
    '|^geo/companies/accommodation?|' => 'accommodation',
    '|^geo/companies/feeding?|' => 'feeding',
    '|^geo/companies/transport?|' => 'transport',
    '|^geo/companies/?|' => 'services',
    '|^geo/places?|' => 'places',


  ];

  foreach ($routes as $src => $dst){
    if (preg_match($src, $path, $matches)){
      $src_array = [];
      foreach ($matches as $key => $match){
        $src_array[] = "{{m$key}}";
      }
      $path = str_replace($src_array, $matches, $dst);
      break;
    }
  }
}