<?php

/**
 * Implements hook_menu().
 */
function palom_content_menu_menu() {
  $items = [];

  $items['node/%node/view/descr'] = [
    'title' => 'Description',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  ];
/*
  $items['geo/companies'] = [
    'title' => 'Организация паломничеств',
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
  ];
*/
  return $items;
}

/**
 * Implements hook_url_inbound_alter().
 */
function palom_content_menu_url_inbound_alter(&$path, $original_path, $path_language) {

  $routes = [

    // by city
    '|^city/([0-9]*)/places?|' => 'node/{{m1}}/view/placesbycity',
    '|^city/([0-9]*)/services?|' => 'node/{{m1}}/view/servicesbycity',
    '|^city/([0-9]*)/accommodation?|' => 'node/{{m1}}/view/accommodationbycity',
    '|^city/([0-9]*)/feeding?|' => 'node/{{m1}}/view/feedingbycity',
    '|^city/([0-9]*)/transport?|' => 'node/{{m1}}/view/transportbycity',

    // by place

    // by service
    '|^service/([0-9]*)/tours?|' => 'node/{{m1}}/view/toursby',

  ];

  foreach ($routes as $src => $dst){
    if (preg_match($src, $path, $matches)){
      $src_array = [];
      foreach ($matches as $key => $match){
        $src_array[] = "{{m$key}}";
      }
      $path = str_replace($src_array, $matches, $dst);
    }
  }

  /*
  // Tours from service
  if (preg_match('|^service/([0-9]*)/tours?|', $path, $matches)) {
    $path = 'node/'.$matches[1].'/toursby';
  }

  // By city
  if (preg_match('|^city/([0-9]*)/places?|', $path, $matches)) {
    $path = 'node/'.$matches[1].'/view/placesbycity';
  }
  */

}

/**
 * Implements hook_url_outbound_alter().
 */
function palom_content_menu_url_outbound_alter(&$path, &$options, $original_path) {

  $routes = [

    // by city
    '|^node/([0-9]*)/view/placesbycity?|' => 'city/{{m1}}/places',
    '|^node/([0-9]*)/view/servicesbycity?|' => 'city/{{m1}}/services',
    '|^node/([0-9]*)/view/accommodationbycity?|' => 'city/{{m1}}/accommodation',
    '|^node/([0-9]*)/view/feedingbycity?|' => 'city/{{m1}}/feeding',
    '|^node/([0-9]*)/view/transportbycity?|' => 'city/{{m1}}/transport',


    // by place


    // by service
    '|^node/([0-9]*)/view/toursby?|' => 'service/{{m1}}/tours',


  ];

  foreach ($routes as $src => $dst){
    if (preg_match($src, $path, $matches)){
      $src_array = [];
      foreach ($matches as $key => $match){
        $src_array[] = "{{m$key}}";
      }
      $path = str_replace($src_array, $matches, $dst);
    }
  }
/*
  // Tours from service
  if (preg_match('|^node/([0-9]*)/toursby?|', $path, $matches)) {
    $path = 'service/'.$matches[1].'/tours';
  }

  // By city
  if (preg_match('|^node/([0-9]*)/view/placesbycity?|', $path, $matches)) {
    $path = 'city/'.$matches[1].'/places';
  }
*/
}