<?php

/**
 * Implements hook_libraries_info().
 */
function palom_libs_libraries_info() {
  $libraries['bootstrap_datepicker'] = [
    'name' => 'Bootstrap datepicker',
    'vendor url' => 'https://www.eyecon.ro/bootstrap-datepicker',
    'version' => '1.0.0',
    'files' => [
      'js' => [
        'bootstrap-datepicker.js',
      ],
      'css' => [
        'datepicker.css',
      ],
    ],
  ];

  $libraries['bootstrap_treeview'] = [
    'name' => 'Bootstrap TreeView',
    'vendor url' => 'https://github.com/jonmiles/bootstrap-treeview',
    'version' => '1.2.0',
    'files' => [
      'js' => [
        'bootstrap-treeview.js',
      ],
      'css' => [
        'bootstrap-treeview.css',
      ],
    ],
    'variants' => [
      'minified' => [
        'files' => [
          'js' => [
            'bootstrap-treeview.min.js',
          ],
          'css' => [
            'bootstrap-treeview.min.css',
          ],
        ],
      ]
    ]
  ];

  $libraries['fancytree'] = [
    'name' => 'JQuery fancyTree',
    'vendor url' => 'https://github.com/mar10/fancytree',
    'version' => '2.3.0',
    'files' => [
      'js' => [
        'jquery.fancytree-all.js',
      ],
      'css' => [
//        'skin-lion/ui.fancytree.css',
        'ui.fancytree.css',
      ],
    ],
//    'variants' => [
//      'minified' => [
//        'files' => [
//          'js' => [
//            'jquery.fancytree-custom.min.js',
//          ],
//          'css' => [
////            'skin-lion/ui.fancytree.min.css',
//            'ui.fancytree.min.css',
//          ],
//        ],
//      ]
//    ]
  ];

  $libraries['sprintf'] = [
    'name' => 'Sprintf',
    'version' => '1.0.0',
    'files' => [
      'js' => [
        'sprintf.js',
      ],
    ],
  ];

  return $libraries;
}

/**
 * Implements hook_libraries_info_alter().
 */
function palom_libs_libraries_info_alter(&$libraries) {
  $libraries['flip']['download file url'] = 'https://cdn.rawgit.com/nnattawat/flip/master/dist/jquery.flip.min.js';
  $libraries['flip']['path'] = 'dist';
  $libraries['flip']['files']['js'] = ['dist/jquery.flip.min.js'];
  $libraries['flip']['version arguments']['file'] = 'dist/jquery.flip.min.js';
}