<?php

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function palom_form_custom_field_widget_mvf_widget_default_form_alter(&$element, &$form_state, $context) {
  if (in_array($element['#field_name'], ['field_avg_cost', 'field_cost'])){
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function palom_form_custom_form_node_form_alter(&$form, &$form_state, $form_id) {
  //kpr($form_id);
//  kpr($form);
//  $form['#fieldgroups']['group_main']['#theme'] = 'tour_group_main';
  /*
  switch($form_id){
    case 'pilgrim_service_node_form':
      $form['#theme'] = ['pilgrim_service_node_form'];
      break;
    case 'accommodation_node_form':
      $form['#theme'] = ['accommodation_node_form'];
      break;
    case 'feeding_node_form':
      $form['#theme'] = ['feeding_node_form'];
      break;
    case 'transport_node_form':
      $form['#theme'] = ['transport_node_form'];
      break;
    case 'tour_node_form':
      $form['#theme'] = ['tour_node_form'];
      break;
    case 'review_node_form':
      $form['#theme'] = ['review_node_form'];
      break;
  }
  */
}

/**
 * Implements hook_theme().
 */
function palom_form_custom_theme($existing, $type, $theme, $path) {
  return [
    'tour_group_main' => [
      'render element' => 'element',
      'template' => 'tour-group-main',
      'path' => drupal_get_path('theme', 'palom').'/templates/form',
    ]
//    'pilgrim_service_node_form' => [
//      'render element' => 'form',
//      'template' => 'pilgrim-service-node-form',
//      'path' => drupal_get_path('theme', 'palom').'/templates/form',
//    ],
//    'accommodation_node_form' => [
//      'render element' => 'form',
//      'template' => 'accommodation-node-form',
//      'path' => drupal_get_path('theme', 'palom').'/templates/form',
//    ],
//    'feeding_node_form' => [
//      'render element' => 'form',
//      'template' => 'feeding-node-form',
//      'path' => drupal_get_path('theme', 'palom').'/templates/form',
//    ],
//    'transport_node_form' => [
//      'render element' => 'form',
//      'template' => 'transport-node-form',
//      'path' => drupal_get_path('theme', 'palom').'/templates/form',
//    ],
//    'tour_node_form' => [
//      'render element' => 'form',
//      'template' => 'tour-node-form',
//      'path' => drupal_get_path('theme', 'palom').'/templates/form',
//    ],
//    'review_node_form' => [
//      'render element' => 'form',
//      'template' => 'review-node-form',
//      'path' => drupal_get_path('theme', 'palom').'/templates/form',
//    ],
  ];
}

