<?php

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function palom_form_custom_field_widget_mvf_widget_default_form_alter(&$element, &$form_state, $context) {
  if (in_array($element['#field_name'], ['field_avg_cost', 'field_cost'])){
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function palom_form_custom_form_node_form_alter(&$form, &$form_state, $form_id) {
}