<?php

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function palom_form_custom_field_widget_mvf_widget_default_form_alter(&$element, &$form_state, $context) {
  if (in_array($element['#field_name'], ['field_avg_cost', 'field_cost'])){
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function palom_form_custom_form_place_node_form_alter(&$form, &$form_state, $form_id) {
//  kpr($form);
  foreach ($form['field_place_type']['und']['#options'] as &$value){
    $value = trim($value, "-");
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function palom_form_custom_form_user_register_form_alter(&$form, &$form_state, $form_id) {
//  $form['#theme'] = 'palom_user_register';
}

/**
 * Implements hook_theme().
 */
function palom_form_custom_theme($existing, $type, $theme, $path) {
  return [
    'palom_user_register' => [
      'render element' => 'form',
      'template' => 'user-register-form',
      'path' => drupal_get_path('theme', 'palom').'/templates/form',
    ],
  ];
}

