<?php

require_once 'palom_utils.func.inc';

/**
 * Implements hook_menu().
 */
function palom_utils_menu() {
  $items = [];

  $items['palom-get-info/get-region-and-city-by-geo'] = [
    'page callback' => '_palom_utils_get_region_city_by_geo',
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];

  $items['palom-get-info/get-region-city-place-by-geo'] = [
    'page callback' => '_palom_utils_get_region_city_place_by_geo',
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];

  $items['test'] = [
    'title' => t('A test page to output data'),
    'page callback' => 'palom_utils_test_callback',
    'access arguments' => ['administer content'],
    'type' => MENU_CALLBACK,
  ];

  $items['palom-get-info/get-last-nid'] = [
    'page callback' => '_palom_utils_get_last_nid',
    'file' => 'palom_utils.func.inc',
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];

  return $items;
}

function palom_utils_test_callback(){

//  _palom_currency_update_rates();
//  _palom_currency_update_amount('node', 74, 'field_avg_cost');
//  _palom_currency_update_amount_bundle('node', 'accommodation', ['field_avg_cost']);



  $query = db_select('field_data_field_state', 'state');
  $query->addField('state', 'field_state_first', 'state_value');
  $query->innerJoin('field_data_field_owners', 'owners', 'state.entity_id = owners.field_owners_target_id');
  $query->innerJoin('field_data_field_services', 'services', 'owners.entity_id = services.field_services_target_id');
  $query->condition('services.entity_id', 79);
  $query->condition('services.bundle', 'tour');
  $query->condition('state.field_state_second', date('Y-m-d'), '>=');

//  kpr($query->__toString());

  $values = $query->execute()->fetchCol();

  if ($values == [])
    $result = 10;
  else
    $result = max($values);

  return 'Test page';
}

/*
 * Get region and city by geo menu callback
 */
function _palom_utils_get_region_city_by_geo($geo_id){
  drupal_json_output(palom_utils_get_region_city_by_geo($geo_id));
}

/*
 * Get region, city and place structure by geo menu callback
 */
function _palom_utils_get_region_city_place_by_geo($geo_id){
  drupal_json_output(palom_utils_get_region_city_place_by_geo($geo_id));
}

function _palom_utils_get_last_nid($node_type){
  drupal_json_output(palom_utils_get_last_nid($node_type));
}

